---
- name: Create private key
  shell: "wg genkey > /root/wg-private.key"
  args:
    creates: /root/wg-private.key
  become: true

- name: Create public key
  shell: "wg pubkey < /root/wg-private.key > /root/wg-public.key"
  args:
    creates: /root/wg-public.key
  become: true

- name: Make sure only root can read privkey
  file:
    path: /root/wg-private.key
    owner: root
    group: root
    mode: '0600'
  become: true

- name: Get the private key contents
  shell: "cat /root/wg-private.key"
  register: privkey
  become: true

- name: Get the public key contents
  shell: "cat /root/wg-public.key"
  register: pubkey
  become: true

- name: Create configuration directory
  file:
    dest: "/etc/wireguard"
    state: directory
    mode: 0700
  become: true

- name: Ensure configuration is available for wireguard
  template:
    src: templates/wireguard.conf
    dest: /etc/wireguard/wg-fullmesh.conf
    mode: 0644
  become: true

- name: Start and enable wireguard
  service:
    name: "wg-quick@wg-fullmesh"
    state: started
    enabled: yes
  become: true

- name: Add the host entries to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ wireguard_hosts[item].private_ip }} {{ wireguard_hosts[item].private_hostname }} {{ wireguard_hosts[item].private_hostname }}.{{ wireguard_domain }}"
    state: present
  when: inventory_hostname != item
  with_items: "{{ wireguard_hosts }}"
  become: true

- name: Add the localhost host entry to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ wireguard_hosts[inventory_hostname].private_hostname }} {{ wireguard_hosts[inventory_hostname].private_hostname }}.{{ wireguard_domain }}"
    state: present
  become: true
