---
- name: Ensure Gitlab data dir is available
  file:
    path: "{{ gitlab_docker_data_dir }}"
    state: directory
  become: true

# This task is executed even when LFS is not enabled, because we have to
# mount this folder into the docker container
- name: Ensure LFS directory is available
  file:
    path: "{{ gitlab_docker_lfs_storage_path }}"
    state: directory
  become: true

- name: Ensure pip is available
  package:
    name: python-pip
    state: present
  become: true
 
- name: Ensure Python bindings for docker are available, required for ansible
  pip:
    name: docker
  become: true

- name: Ensure GitLab docker image is available
  docker_image:
    name: gitlab/gitlab-ce
    tag: latest
  become: true

- name: Ensure GitLab container is running (public)
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    state: started
    recreate: no
    ports:
      - "{{ gitlab_docker_http_port }}:80"
      - "{{ gitlab_docker_ssh_port }}:{{ gitlab_docker_ssh_port }}"
    volumes:
      - "{{ gitlab_docker_data_dir }}/config:/etc/gitlab"
      - "{{ gitlab_docker_data_dir }}/logs:/var/log/gitlab"
      - "{{ gitlab_docker_data_dir }}/data:/var/opt/gitlab"
      - "{{ gitlab_docker_lfs_storage_path }}:/data/lfs"
    hostname: "{{ gitlab_docker_hostname }}"
  become: true
  when: gitlab_docker_http_public

- name: Ensure GitLab container is running (non-public)
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    state: started
    recreate: no
    ports:
      - "{{ gitlab_docker_ssh_port }}:{{ gitlab_docker_ssh_port }}"
    volumes:
      - "{{ gitlab_docker_data_dir }}/config:/etc/gitlab"
      - "{{ gitlab_docker_data_dir }}/logs:/var/log/gitlab"
      - "{{ gitlab_docker_data_dir }}/data:/var/opt/gitlab"
      - "{{ gitlab_docker_lfs_storage_path }}:/data/lfs"
    hostname: "{{ gitlab_docker_hostname }}"
  become: true
  when: not gitlab_docker_http_public
