# uwsgi has trouble with SSL, see
# https://github.com/unbit/uwsgi/issues/1569
# use gunicorn in the meantime
- name: Use gunicorn as a replacement for uwsgi because of SSL issues
  pip:
    virtualenv: "{{ pidar_install_dir }}/env"
    name: gunicorn

- name: Ensure supervisord is installed for gunicorn
  package:
    name: supervisor
    state: latest
  become: true
  notify: Start supervisor

- name: Ensure supervisor script is installed
  template:
    src: templates/pidar_supervisor.conf
    dest: "/etc/supervisor/conf.d/{{ pidar_name }}.conf"
  become: true
  notify: Restart supervisor
