---
- name: Ensure static directory is available for nginx
  file:
    path: "/var/www/{{ pidar_name }}/public_html"
    state: directory
    recurse: true
    owner: www-data
    group: www-data
  become: true

- name: Ensure Google Webmaster Tools verification is available
  template:
    src: templates/googleverification.html
    dest: "/var/www/{{ pidar_name }}/public_html/{{ pidar_google_verification_filename }}"
  when: pidar_google_verification_filename is defined
