- name: Ensure Python3 is installed
  package:
    name: python3
    state: latest
  become: true

- name: Ensure project is latest state
  git:
    repo: "{{ pidar_repo_url }}"
    dest: "{{ pidar_install_dir }}"
    force: yes
  notify: Reload supervisor

- name: Ensure production settings are set
  template:
    src: templates/dotenv
    dest: "{{ pidar_install_dir }}/.env"
  notify: Reload supervisor

- name: Ensure virtualenv is available and prepared
  pip:
    virtualenv: "{{ pidar_install_dir }}/env"
    virtualenv_python: python3
    requirements: "{{ pidar_install_dir }}/requirements.txt"

- name: Ensure package is installed, so that we have CLI command
  pip:
    name: "{{ pidar_install_dir}}"
    virtualenv: "{{ pidar_install_dir }}/env"

- name: Ensure psycopg2 is available for Postgres connection
  pip:
    name: psycopg2-binary
    virtualenv: "{{ pidar_install_dir }}/env"

- name: Cronjob for Notifications
  cron:
    name: "pidar-notification"
    minute: "*"
    job: "bash -c 'source {{ pidar_install_dir }}/env/bin/activate && pidar send_mail_notifications' && curl {{ pidar_email_healthchecks_url }} > /dev/null"
    state: present

- name: Cronjob for Polls
  cron:
    name: "pidar-polls"
    minute: "*"
    job: "bash -c 'source {{ pidar_install_dir }}/env/bin/activate && pidar execute-polls' && curl {{ pidar_polls_healthchecks_url }} > /dev/null"
    state: present
