---
- name: Ensure aws-cli is installed
  package:
    name: awscli
    state: present
  become: true

- name: Ensure backup script is installed
  template:
    src: templates/backup.j2
    dest: /etc/cron.weekly/backup-mongodb-s3
    remote_src: no
    mode: 0755
  become: true
