---
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Restart Nginx
  service:
    name: nginx
    state: reloaded
    enabled: yes
  become: true

- name: Start supervisor
  service:
    name: supervisor
    state: started
    enabled: yes
  become: true

- name: Restart supervisor
  service:
    name: supervisor
    state: reloaded
    enabled: yes
  become: true
