---
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
  become: true

- name: Start Kibana
  service:
    name: kibana
    state: started
    enabled: yes
  become: true

- name: Restart Kibana
  service:
    name: kibana
    state: restarted
    enabled: yes
  become: true
